# Generated by Django 6.0.4 on 2026-04-13 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('acreage', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('open_now', 'Open Now'), ('busy', 'Busy')], default='healthy', max_length=20)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='parks/')),
                ('condition_index', models.PositiveSmallIntegerField(default=85)),
                ('total_trees', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('reward_points', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='parks.park')),
            ],
        ),
        migrations.CreateModel(
            name='TreeMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_markers', to='parks.park')),
            ],
        ),
    ]
