# Generated by Django 5.1.4 on 2026-04-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
